root_data_dir: ./data/render_people/20230228
smpl_dir: ./data/smpl
checkpoint_path:

image_height: 512
image_width: 512

module_name: attcond_smpl_model

model:
  class_name: primdiffusion.model.${module_name}.BodyDecoder
  n_prims: 1024
  prim_size: 8
  n_pose_dims: 69
  n_pose_enc_channels: 32
  prim_motion_enabled: True
  prim_motion_start_train: 2000
  prim_rt_enabled: False
  smpl_gender: NEUTRAL
  image_height: ${image_height}
  image_width: ${image_width}

rm:
  volradius: 10000.0
  dt: 1.0

optimizer:
  class_name: torch.optim.Adam
  lr: 5e-5

loss:
  class_name: dva.losses.TotalMVPLoss
  weights:
    rgb_mse: 1.0
    mask_mae: 0.01
    prim_vol_sum: 0.001
    alpha_prior: 1.0
    vgg: 1.0

train:
  batch_size: 24
  n_epochs: 10000
  n_max_iters: 1000000
  log_every_n_steps: 20
  summary_every_n_steps: 1000
  ckpt_every_n_steps: 10000
  gradient_clip_value: 5.0

cameras_train:
  [
    "00",
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
  ]

cameras_cond: ["00",]

tag: ${module_name}_stage1_fitting
output_dir: ${root_data_dir}/../training-logs/${tag}

# using only T-pose frame
ref_frame: 0

data:
  root_dir: ${root_data_dir}
  subject_ids: ${root_data_dir}/release_human_list.txt
  image: ${root_data_dir}/{people_id}/img/{camera}/{frame:04d}.jpg
  image_mask: ${root_data_dir}/{people_id}/mask/{camera}/{frame:04d}.png
  image_part_mask: ${root_data_dir}/{people_id}/mask/{camera}/{frame:04d}.png
  smpl_poses: ${root_data_dir}/{people_id}/outputs_re_fitting/refit_smpl_2nd.npz
  cam_path: ${root_data_dir}/{people_id}/cameras.json
  smpl_topology: ${smpl_dir}/SMPL_${model.smpl_gender}.pkl
